<?php
use CodeIgniter\Router\RouteCollection;
/** @var RouteCollection $routes */
$routes->get('/', function() { return redirect()->to('/login'); });

$routes->group('', ['filter' => 'guest'], function($routes) {
    $routes->get('login', 'Auth\AuthController::login');
    $routes->post('login', 'Auth\AuthController::loginProcess');
    $routes->get('register', 'Auth\AuthController::register');
    $routes->post('register', 'Auth\AuthController::registerProcess');
    $routes->get('forgot-password', 'Auth\AuthController::forgotPassword');
    $routes->post('forgot-password', 'Auth\AuthController::forgotPasswordProcess');
    $routes->get('reset-password/(:segment)', 'Auth\AuthController::resetPassword/$1');
    $routes->post('reset-password', 'Auth\AuthController::resetPasswordProcess');
});
$routes->get('logout', 'Auth\AuthController::logout');

$routes->group('admin', ['filter' => 'authAdmin'], function($routes) {
    $routes->get('dashboard', 'Admin\DashboardController::index');
    $routes->get('menu', 'Admin\MenuController::index');
    $routes->get('menu/create', 'Admin\MenuController::create');
    $routes->post('menu/store', 'Admin\MenuController::store');
    $routes->get('menu/edit/(:num)', 'Admin\MenuController::edit/$1');
    $routes->post('menu/update/(:num)', 'Admin\MenuController::update/$1');
    $routes->get('menu/delete/(:num)', 'Admin\MenuController::delete/$1');
    $routes->get('users', 'Admin\UserController::index');
    $routes->get('users/delete/(:num)', 'Admin\UserController::delete/$1');
    $routes->get('backup', 'Admin\BackupController::index');
    $routes->get('backup/download', 'Admin\BackupController::download');
    $routes->get('backup/delete/(:segment)', 'Admin\BackupController::deleteFile/$1');
    $routes->get('income', 'Admin\TransactionController::income');
    $routes->get('income/create', 'Admin\TransactionController::createIncome');
    $routes->post('income/store', 'Admin\TransactionController::storeIncome');
    $routes->get('income/edit/(:num)', 'Admin\TransactionController::editIncome/$1');
    $routes->post('income/update/(:num)', 'Admin\TransactionController::updateIncome/$1');
    $routes->get('income/delete/(:num)', 'Admin\TransactionController::deleteIncome/$1');
    $routes->get('expense', 'Admin\TransactionController::expense');
    $routes->get('expense/create', 'Admin\TransactionController::createExpense');
    $routes->post('expense/store', 'Admin\TransactionController::storeExpense');
    $routes->get('expense/edit/(:num)', 'Admin\TransactionController::editExpense/$1');
    $routes->post('expense/update/(:num)', 'Admin\TransactionController::updateExpense/$1');
    $routes->get('expense/delete/(:num)', 'Admin\TransactionController::deleteExpense/$1');
    $routes->get('saving', 'Admin\SavingController::index');
    $routes->get('saving/create', 'Admin\SavingController::create');
    $routes->post('saving/store', 'Admin\SavingController::store');
    $routes->get('saving/edit/(:num)', 'Admin\SavingController::edit/$1');
    $routes->post('saving/update/(:num)', 'Admin\SavingController::update/$1');
    $routes->get('saving/delete/(:num)', 'Admin\SavingController::delete/$1');
    $routes->get('saving/detail/(:num)', 'Admin\SavingController::detail/$1');
    $routes->post('saving/deposit/(:num)', 'Admin\SavingController::deposit/$1');
    $routes->post('saving/withdraw/(:num)', 'Admin\SavingController::withdraw/$1');
    $routes->get('debt', 'Admin\DebtController::index');
    $routes->get('debt/create', 'Admin\DebtController::create');
    $routes->post('debt/store', 'Admin\DebtController::store');
    $routes->get('debt/edit/(:num)', 'Admin\DebtController::edit/$1');
    $routes->post('debt/update/(:num)', 'Admin\DebtController::update/$1');
    $routes->get('debt/delete/(:num)', 'Admin\DebtController::delete/$1');
    $routes->get('debt/detail/(:num)', 'Admin\DebtController::detail/$1');
    $routes->post('debt/pay/(:num)', 'Admin\DebtController::pay/$1');
    $routes->get('report', 'Admin\ReportController::index');
    $routes->get('report/export-pdf', 'Admin\ReportController::exportPdf');
    $routes->get('report/export-excel', 'Admin\ReportController::exportExcel');
    $routes->get('report/export-csv', 'Admin\ReportController::exportCsv');
    $routes->get('report/yearly', 'Admin\ReportController::yearly');
    $routes->get('profile', 'Admin\ProfileController::index');
    $routes->post('profile/update', 'Admin\ProfileController::update');
    $routes->post('profile/change-password', 'Admin\ProfileController::changePassword');
    $routes->get('category', 'Admin\CategoryController::index');
    $routes->get('category/create', 'Admin\CategoryController::create');
    $routes->post('category/store', 'Admin\CategoryController::store');
    $routes->get('category/edit/(:num)', 'Admin\CategoryController::edit/$1');
    $routes->post('category/update/(:num)', 'Admin\CategoryController::update/$1');
    $routes->get('category/delete/(:num)', 'Admin\CategoryController::delete/$1');
});

$routes->group('user', ['filter' => 'authUser'], function($routes) {
    $routes->get('dashboard', 'User\DashboardController::index');
    $routes->get('income', 'User\TransactionController::income');
    $routes->get('income/create', 'User\TransactionController::createIncome');
    $routes->post('income/store', 'User\TransactionController::storeIncome');
    $routes->get('income/edit/(:num)', 'User\TransactionController::editIncome/$1');
    $routes->post('income/update/(:num)', 'User\TransactionController::updateIncome/$1');
    $routes->get('income/delete/(:num)', 'User\TransactionController::deleteIncome/$1');
    $routes->get('expense', 'User\TransactionController::expense');
    $routes->get('expense/create', 'User\TransactionController::createExpense');
    $routes->post('expense/store', 'User\TransactionController::storeExpense');
    $routes->get('expense/edit/(:num)', 'User\TransactionController::editExpense/$1');
    $routes->post('expense/update/(:num)', 'User\TransactionController::updateExpense/$1');
    $routes->get('expense/delete/(:num)', 'User\TransactionController::deleteExpense/$1');
    $routes->get('saving', 'User\SavingController::index');
    $routes->get('saving/create', 'User\SavingController::create');
    $routes->post('saving/store', 'User\SavingController::store');
    $routes->get('saving/edit/(:num)', 'User\SavingController::edit/$1');
    $routes->post('saving/update/(:num)', 'User\SavingController::update/$1');
    $routes->get('saving/delete/(:num)', 'User\SavingController::delete/$1');
    $routes->get('saving/detail/(:num)', 'User\SavingController::detail/$1');
    $routes->post('saving/deposit/(:num)', 'User\SavingController::deposit/$1');
    $routes->post('saving/withdraw/(:num)', 'User\SavingController::withdraw/$1');
    $routes->get('debt', 'User\DebtController::index');
    $routes->get('debt/create', 'User\DebtController::create');
    $routes->post('debt/store', 'User\DebtController::store');
    $routes->get('debt/edit/(:num)', 'User\DebtController::edit/$1');
    $routes->post('debt/update/(:num)', 'User\DebtController::update/$1');
    $routes->get('debt/delete/(:num)', 'User\DebtController::delete/$1');
    $routes->get('debt/detail/(:num)', 'User\DebtController::detail/$1');
    $routes->post('debt/pay/(:num)', 'User\DebtController::pay/$1');
    $routes->get('report', 'User\ReportController::index');
    $routes->get('report/export-pdf', 'User\ReportController::exportPdf');
    $routes->get('report/export-excel', 'User\ReportController::exportExcel');
    $routes->get('report/export-csv', 'User\ReportController::exportCsv');
    $routes->get('report/yearly', 'User\ReportController::yearly');
    $routes->get('notifications', 'User\NotificationController::index');
    $routes->get('notifications/read/(:num)', 'User\NotificationController::markRead/$1');
    $routes->get('notifications/read-all', 'User\NotificationController::markAllRead');
    $routes->get('notifications/delete/(:num)', 'User\NotificationController::delete/$1');
    $routes->get('profile', 'User\ProfileController::index');
    $routes->post('profile/update', 'User\ProfileController::update');
    $routes->post('profile/change-password', 'User\ProfileController::changePassword');
    $routes->get('category', 'User\CategoryController::index');
    $routes->get('category/create', 'User\CategoryController::create');
    $routes->post('category/store', 'User\CategoryController::store');
    $routes->get('category/edit/(:num)', 'User\CategoryController::edit/$1');
    $routes->post('category/update/(:num)', 'User\CategoryController::update/$1');
    $routes->get('category/delete/(:num)', 'User\CategoryController::delete/$1');
});
